name: Frontend

on:
    workflow_dispatch:
    push:

jobs:
    frontend-style:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.8.1
              with:
                  cache: yarn
                  cache-dependency-path: yarn.lock

            - name: Install Dependencies
              run: yarn

            - name: Frontend Styling
              run: yarn run style:test

    frontend-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.8.1
              with:
                  cache: yarn
                  cache-dependency-path: yarn.lock

            - name: Install Dependencies
              run: yarn

            - name: Frontend Styling
              run: yarn run lint:test

    frontend-type:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v3.8.1
              with:
                  cache: yarn
                  cache-dependency-path: yarn.lock

            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl, gd, exif
                  coverage: none

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Backend Dependencies
              run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            - name: Install Fontend Dependencies
              run: yarn

            - name: Frontend Type
              run: yarn run type:test
